### ISSUE TITLE
First Name doesnt let me click...

### ISSUE THREAD

**Issue by maiya-maxwell** [maiya-maxwell/DIG103A#2]
https://maiya-maxwell.github.io/DIG103A/ASSESSMENT_4/contact.html

`<input type="text" placeholder="first name" name="name">
<input type="text" placeholder="last name" name="name"> <br> `

**Comment by rhaubt** [comment]
Hi,
Your h2 Contact h2 header element is too high and overlaps with the text field. The text field works but because the contact h2 is too high it covers the text field. Have a look in the Inspector tool in your browser.

`header h2 {
    padding-top: 50px;
    padding-bottom: 100px; /*  change this to eg 50px*/ 
}`

let me know if this worked and close the issue :D

**Comment by maiya-maxwell** [comment]
Ah huh! Thank you
